[book]
authors = ["Restos du Coeur"]
language = "fr"
multilingual = false
src = "src"
title = "Prometheus Alerting Rules Collection"

[output.html]
additional-css = ["theme/custom.css"]
additional-js = ["theme/custom.js"]
git-repository-url = "https://github.com/cloudducoeur/collection-prometheus-alerting-rules"
